# === Энергосбережение ===
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=60000
CONFIG_ZMK_SLEEP=y

# === BLE стабильность ===
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=80
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=40
CONFIG_BT_PERIPHERAL_PREF_LATENCY=10
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# === USB Логирование (только это добавь) ===
CONFIG_ZMK_USB_LOGGING=y
CONFIG_SERIAL=y
